### ISSUE TITLE
innerHTML does not render

### ISSUE THREAD

**Issue by markwylde** [MithrilJS/mithril-node-render#101]
## Example:
```javascript
m('div', { innerHTML: 'Hello <b>there</b>' }, 'No Thanks')
```

## Result:
```javascript
<div innerHTML="Hello &lt;b&gt;there&lt;/b&gt;"></div>
```

## Expected
```javascript
<div>Hello <b>there</b></div>
```

I've started a [pull request](https://github.com/MithrilJS/mithril-node-render/pull/100) with a failing test.

**Comment by StephanHoyer** [comment]
[Mithril itself](https://www.flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+LLQCuDABQATWtSk4G+AEa15ATwoACYAB00evQDcIMAO6I9sgJR6AvAD49WWQHJ5EM5-3AehBoaDAATgASACoAsgAytp4RMFBQtHoAPOouxIThMBkA9Nmeeux6ngBy6VGEGGgA1nCejnrGrPbGlCBwKTDUxBD0CDwADIgA7GwcIJg4ePjUcAI09IzMPGwAulRQwU1IqLNcYhC5YdDdUmHkPCTEAA5wiIWFMg8NAOaLtFiFWGdCBcoAABABM+FG+AALP9AcCJMF8PxusRtA9uD1qBcHqJWDtjvMeADztBkQhWEA) does not render `innerHTML`, so mnr should not too.

What you probably want is [`m.trust`](https://www.flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+LLQCuDABQATWtSk4G+AEa15ATwoACYAB00evQDcIMAO6I9sgJR6AvAD49WWQHJ5EM5-2eAHK0egAqhBhoANZw-u74xABOUnDEXgASMFBQIQA86i7EhDCJMLkA9AWe9o56xqz2xpQgcFkw1MQQ9Ag8AIyIAGwALGwcIJg4ePjUcAI09IzMPGwAulRQENE9qONcYhBFidDNUonkPCTEAA5wiOXlMldRAObTtFjlWAeER1AAAgAmfAABnwQ0+31+Ek2+H4zWI2iu3Ba1COV1ErDWu0mPC+h2gsIQrCAA)

**Comment by markwylde** [comment]
It does [in this scenario](https://www.flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+LLQCuDABQATWtSk4G+AEa15ATwoACYAB00evQDcIMAO6I9sgJR6AvAD49WWQHJ5EM5-3AehBoaDAATgASACoAsgAytp4RMFBQtHoAPOouxIThMBkA9NmeeqyOesblxpQgcCkw1MQQ9Ag8AMyIAAxsHCCYOHj41HACNPSMzDxsALpUUMEA1m2o-VxiELlh0LVSYeQ8JMQADnCIhYUyx4sA5sO0WIVYm4TbUAACAEz4XfgALE8Xm8JMF8PxasRtMduHVqNtjqJWHM1oMeM8ttAwQhWEA)

**Comment by isiahmeadows** [comment]
@markwylde Mithril proper just does `vnode.dom.innerHTML = ...`. It doesn't actually do anything special to support it.

So technically mithril-node-render is consistent with Mithril. I could see the value in adding this as a feature request, though. /cc @StephanHoyer
