### ISSUE TITLE
Add support to render sync

### ISSUE THREAD

**Issue by gaheinrichs** [MithrilJS/mithril-node-render#65]
I am interested on running this library embedded in a .NET application using [JavaScriptEngineSwitcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher)

Getting back a string when executing render will be ideal.

 Is there any way to be able to:
`var html = render(m('div', 'Hello'))`
`//<div>Hello</div>`

I don't care on losing the async initialization.

**Comment by dineshselvantdm** [comment]
Is there checksum matcher to avoid redraw during client side mounting?

**Comment by StephanHoyer** [comment]
@gaheinrichs If I have some I will try to work something out.

@dineshselvantdm no, I think this is not the scope of this module. Also mithril currently does not support picking up rendered DOM.
