### ISSUE TITLE
rewrite everything in TypeScript

### ISSUE THREAD

**Issue by tlaziuk** [MithrilJS/mithril-node-render#69]
Hello,

I'm rewriting this package in TypeScript, I don't know yet if the backward compatibilty should be preserved - please advise.

code example - https://github.com/tlaziuk/mithril-node-render/blob/master/index.ts

Would you be interested in merging my code into this repo?

**Comment by StephanHoyer** [comment]
Sorry i am currently on vacation. Will look in 2 weeks or so

**Comment by tlaziuk** [comment]
ok, I'll wait :)

**Comment by StephanHoyer** [comment]
@isiahmeadows pretty much rewrote the whole thing. If you still want to rewrite this, use the current version and create a new PR then
