### ISSUE TITLE
How can i use it with jsx ?

### ISSUE THREAD

**Issue by tavousi** [MithrilJS/mithril-node-render#75]
Hi, there
i use mithril + jsx in my app and i want use this ! how can i do that ?

**Comment by StephanHoyer** [comment]
I think you have to use a jsx-compiler serverside. Haven't tried this, since I don't use jsx.

If you found a solution for this, feel free to drop it here, so that I can include in the docs.

**Comment by alfa-jpn** [comment]
Hi,
I used mithril.js with jsx.

This example is SPA + SSR with jsx.
https://github.com/alfa-jpn/mithril-spa-ssr-example

Without juice(server side css rendering) version is this commit.
https://github.com/alfa-jpn/mithril-spa-ssr-example/tree/e04ca9572eaf05e25c50e1f07ff37e9995b1331c

**Comment by tavousi** [comment]
@alfa-jpn thank you so much.
