### ISSUE TITLE
PSA: I've added a bunch of default community health files org-wide

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril-node-render#92]
Community health files are stuff like CONTRIBUTING.md, FUNDING.yml, and so on, stuff that normally lives in `.github`, `docs/`, or the repo's root. I've added [default files](https://github.com/MithrilJS/.github) for [everything on this list of supported file types](https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization#supported-file-types) except for a CONTRIBUTING.md file, as that process varies pretty greatly across repos. For issue templates, there's two templates: one for bugs and one for feature requests. The pull request template and issue templates are each derived from the core project's own core templates but with core-specific stuff omitted.

No action is required on your part, but you may wish to customize these appropriately and/or take other related action in light of this like adding/removing issue templates.

-----

If you have any questions, comments, or concerns, [please file an issue](https://github.com/MithrilJS/.github) and I'd be more than willing to address them.

**Comment by StephanHoyer** [comment]
thanks

**Comment by isiahmeadows** [comment]
Update: you'll have to copy them over if you have a `.github` since they don't apply piecemeal for some reason. I discovered this the hard way. 😕
