### ISSUE TITLE
Error doc

### ISSUE THREAD

**Issue by souricevincent** [MithrilJS/mithril-node-render#95]
Hello ! 👋 
In your README you say : `Optionally pass in options as an object: m.render(component, options).` but it is `Optionally pass in options as an object: render(component, options).`, no ?

**Comment by isiahmeadows** [comment]
Feel free to file a pull request against the README to fix that. I have literally no clue how none of us thought to fix it... 🤦‍♀️😄

**Comment by souricevincent** [comment]
I'm willing to do PR, but I don't have the permissions...

**Comment by isiahmeadows** [comment]
@souricevincent [You might appreciate this link](https://guides.github.com/activities/forking/) - it should help you get started.

**Comment by souricevincent** [comment]
@isiahmeadows Hello, I sent the correction, can you please merge it if it suits you. Thanks

**Comment by isiahmeadows** [comment]
Sorry, wasn't watching the repo or I would've caught it. (This is primarily maintained by @StephanHoyer.)
